<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-22T15:20:51 GMT-06:00" name="Suite" finished-at="2025-01-22T15:20:51 GMT-06:00" duration-ms="832">
    <groups>
    </groups>
    <test started-at="2025-01-22T15:20:51 GMT-06:00" name="Login Test" finished-at="2025-01-22T15:20:51 GMT-06:00" duration-ms="770">
      <class name="testcases.LoginTest">
        <test-method is-config="true" signature="init()[pri:0, instance:testcases.LoginTest@5552768b]" started-at="2025-01-22T15:20:51 GMT-06:00" name="init" finished-at="2025-01-22T15:20:51 GMT-06:00" duration-ms="269" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="login()[pri:0, instance:testcases.LoginTest@5552768b]" started-at="2025-01-22T15:20:51 GMT-06:00" name="login" finished-at="2025-01-22T15:20:51 GMT-06:00" duration-ms="14" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[404, Error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 404, Error
at org.testng.Assert.fail(Assert.java:97)
at testcases.LoginTest.login(LoginTest.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="quit()[pri:0, instance:testcases.LoginTest@5552768b]" started-at="2025-01-22T15:20:51 GMT-06:00" name="quit" finished-at="2025-01-22T15:20:51 GMT-06:00" duration-ms="427" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- testcases.LoginTest -->
    </test> <!-- Login Test -->
    <test started-at="2025-01-22T15:20:51 GMT-06:00" name="Registration Test" finished-at="2025-01-22T15:20:51 GMT-06:00" duration-ms="18">
      <class name="testcases.RegistrationTest">
        <test-method is-config="true" signature="init()[pri:0, instance:testcases.RegistrationTest@482bce4f]" started-at="2025-01-22T15:20:51 GMT-06:00" name="init" finished-at="2025-01-22T15:20:51 GMT-06:00" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="register()[pri:0, instance:testcases.RegistrationTest@482bce4f]" started-at="2025-01-22T15:20:51 GMT-06:00" name="register" finished-at="2025-01-22T15:20:51 GMT-06:00" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method is-config="true" signature="quit()[pri:0, instance:testcases.RegistrationTest@482bce4f]" started-at="2025-01-22T15:20:51 GMT-06:00" name="quit" finished-at="2025-01-22T15:20:51 GMT-06:00" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- testcases.RegistrationTest -->
    </test> <!-- Registration Test -->
  </suite> <!-- Suite -->
</testng-results>
